### ISSUE TITLE
Hi, what is the purpose of this project, can we use it to perform scanning on Windows

### ISSUE THREAD

**Issue by dbabel** [paulsouche/node-twain-dll#1]
Hi,
There seems to be no docs to explain what is this project about. I am interested to know if it is a node module which can interact with twain based scanners installed on my windows machine to get the scanning done. Can you please provide more information about it??
Thank you, your help is really appreciated.

**Comment by paulsouche** [comment]
Hi,

Sorry for being late but I never found a node module that do this. Our purpose is the same indeed... And that's why I opened this repo.

Unfortunatly I opened it with another co-worker and we moved on others projects instead. But this is always in the pipe of what must be done.

Follow us on next episode

**Comment by dbabel** [comment]
Hi,
Thanks for the reply Paul. Though by now, we have something working in place for us.
